config/routes.rb
Rails.application.routes.draw do

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	devise_for :users, controllers: { registrations: 'registrations' }

	root 'posts#index'
	root 'posts#new'

	resources :posts do
		resources :comments
		member do
			get 'like'
			get 'dislike'
		end
	end

	# notifications routes
	get 'notifications', to: 'notifications#index'
	get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

	# WARNING - since the profiles use any unmatched string as a username, these routes have to be the last thing to be checked!
	# profiles routes
	get 'profiles/show'
	get ':user_name', to: 'profiles#show', as: :profile
	get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
	patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  # with every new post object that’s created we need an associated `user_id` and `image`
  validates :user_id, presence: true

  validates :content, presence: true, length: { minimum: 3, maximum: 300 }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_post

	def index
		@comments = @post.comments.order('created_at ASC')

		respond_to do |format|
			format.html { render layout: !request.xhr? }
		end
	end

	def create
		@comment = @post.comments.build(comment_params)
		@comment.user_id = current_user.id

		if @comment.save

			# generate a notification for the successful act of creating a comment
			create_notification @post, @comment

			# dynamic reload with AJAX
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		else
			flash[:alert] = 'Check the comment form, somethign went horribly wrong!'
			render root_path
		end
	end

	def destroy
		@comment = @post.comments.find(params[:id])

		if @comment.user_id == current_user.id
			@comment.destroy
			# dynamic reload with AJAX
			respond_to do |format|
				format.html { redirect_to root_path }
				format.js
			end
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:content)
	end

	def set_post
		@post = Post.find(params[:post_id])
	end

	def create_notification(post, comment)
		# don't notify the current user if he owns the post
		return if post.user_id == current_user.id
		Notification.create(user_id: post.user_id, notified_by_user_id: current_user.id, post_id: post.id, comment_id: comment.id, notification_type: 'comment')
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="comment">
	<%= profile_link(comment.user) %>
	<div class="comment-content">
		<%= comment.content %>
	</div>
	<% if comment.user == current_user %>
		<%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
			<span class="glyphicon glyphicon-remove delete-comment"></span>
		<% end %>
	<% end %>
</div>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/comments/index.html.erb
<%= render @comments, post: @post %>