config/routes.rb
Rails.application.routes.draw do

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	devise_for :users, controllers: { registrations: 'registrations' }

	root 'posts#index'
	root 'posts#new'

	resources :posts do
		resources :comments
		member do
			get 'like'
			get 'dislike'
		end
	end

	# notifications routes
	get 'notifications', to: 'notifications#index'
	get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

	# WARNING - since the profiles use any unmatched string as a username, these routes have to be the last thing to be checked!
	# profiles routes
	get 'profiles/show'
	get ':user_name', to: 'profiles#show', as: :profile
	get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
	patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/notification.rb
class Notification < ApplicationRecord
	
	belongs_to :notified_by_user, class_name: 'User'
	belongs_to :user
	belongs_to :post
	belongs_to :comment, optional: true

	validates :user_id, :notified_by_user_id, :post_id, :notification_type, presence: true

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController

	before_action :set_notification, only: %i[link_through]

	def index
		@notifications = current_user.notifications.order('created_at DESC').page params[:page]
		# ajax request will result in request.xhr? not nil
		# layout will be true if request is not an ajax request
		render action: :index, layout: request.xhr?.nil?
	end

	def link_through
		@notification.update read: true
		redirect_to post_path @notification.post
	end

	private

	def set_notification
		@notification = Notification.find(params[:id])
	end

end

app/helpers/notifications_helper.rb
module NotificationsHelper

	def notification_alert_message(notification)
		user = User.find(notification.notified_by_user_id)
		return "#{user.user_name} liked your post" if notification.notification_type == 'like'
		"#{user.user_name} commented on your post"
	end

end

app/views/notifications/_notification.html.erb
<!-- show the 10 latest notifications -->
<% current_user.notifications.order('created_at DESC').limit(10).each do |notification| %>

<a href="<%= link_through_path(notification)%>" style="text-decoration:none;">
	<li class="notifications-dropdown-item" id="<%= notification.id %>" >

		<div class="<%= notification.read ? "read-notification" : "unread-notification" %>">
			<%= notification_alert_message notification %>
			<br>
			<small> <%= time_ago_in_words notification.created_at %> </small>
		</div>

	</li>
</a>
<% end %>

app/views/notifications/_notification_dropdown.html.erb
<div class="dropdown notification-dropdown">

	<button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1", data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		<!-- count the unread notifications -->
		<%= current_user.notifications.select{ |item| !item[:read] }.count %>
		<span class="glyphicon glyphicon-flag"></span>
	</button>

	<ul class="dropdown-menu">

		<li>
			<div class="dropdown-header text-center">
				Notifications
			</div>
		</li>

		<!-- render the notifications -->
		<% @notifications.each do |notification| %>
			<%= render 'notification', notification: notification %>
		<% end %>

		<li class="divider" role="separator">
			<li class="text-center">
				<%= link_to 'View All', notifications_path %>
			</li>
		</li>

	</ul>
</div>

app/views/notifications/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<ul class="notification-index-list" id="notifications">
				<% @notifications.each do |notification| %>
					<%= render 'notification', notification: notification %>
				<% end %>
			</ul>
		</div>
	</div>
</div>

<div class="text-center" id="paginator">
	<%= link_to_next_page @notifications, 'Load More', remote: true, id: 'load_more' %>
</div>

app/views/notifications/index.js.erb
$('#notifications').append("<%= escape_javascript(render 'notifications') %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@notifications, 'Load More', remote: true, id: 'load_more')) %>")
if (!$('#load_more').length) { $('#paginator').remove(); }