config/routes.rb
Rails.application.routes.draw do

	# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	devise_for :users, controllers: { registrations: 'registrations' }

	root 'posts#index'
	root 'posts#new'

	resources :posts do
		resources :comments
		member do
			get 'like'
			get 'dislike'
		end
	end

	# notifications routes
	get 'notifications', to: 'notifications#index'
	get 'notifications/:id/link_through', to: 'notifications#link_through', as: :link_through

	# WARNING - since the profiles use any unmatched string as a username, these routes have to be the last thing to be checked!
	# profiles routes
	get 'profiles/show'
	get ':user_name', to: 'profiles#show', as: :profile
	get ':user_name/edit', to: 'profiles#edit', as: :edit_profile
	patch ':user_name/edit', to: 'profiles#update', as: :update_profile

end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_votable

  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy

  # with every new post object that’s created we need an associated `user_id` and `image`
  validates :user_id, presence: true
  validates :image, presence: true

  has_attached_file :image, styles: { medium: '640x' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: %i[show edit update destroy like dislike]
	before_action :owned_post, only: %i[edit update destroy]

	# actions

	def index
		@posts = Post.all.order('created_at DESC').page params[:page]
		# ajax request will result in request.xhr? not nil
		# layout will be true if request is not an ajax request
		render action: :index, layout: request.xhr?.nil?
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			flash[:success] = 'Your post was successfully created!'
			redirect_to posts_path
		else
			flash.now[:alert] = "Your new post couldn't be created! Please check the form."
			render :new
		end
	end

	def show; end

	def edit; end

	def update
		if @post.update(post_params)
			flash[:success] = 'Your post was successfully updated!'
			redirect_to(posts_path(@post))
		else
			flash.now[:alert] = "Your new post couldn't be updated! Please check the form."
			render :edit
		end
	end

	def destroy
		@post.destroy
		flash[:success] = 'Your post was successfully deleted!'
		redirect_to posts_path
	end

	def like
		current_user.likes @post

		# generate a notification for the successful act of liking a post
		create_like_notification @post

		respond_to do |format|
			format.html { redirect_to :back }
			format.js
		end
	end

	def dislike
		current_user.dislikes @post

		# delete a notification for previously liking a post
		delete_like_notification @post

		respond_to do |format|
			format.html { redirect_to :back }
			format.js
		end
	end

	private

	def post_params
		params.require(:post).permit(:image, :caption)
	end

	def set_post
		@post = Post.find(params[:id])
	end

	def owned_post
		unless current_user == @post.user
			flash[:alert] = "That post doesn't belong to you!"
			redirect_to root_path
		end
	end

	def create_like_notification(post)
		# don't notify the current user if he owns the post
		return if post.user_id == current_user.id
		 Notification.create(user_id: post.user_id, notified_by_user_id: current_user.id, post_id: post.id, notification_type: 'like')
	end

	def delete_like_notification(post)
		notification = Notification.find_by(user_id: post.user_id, notified_by_user_id: current_user.id, post_id: post.id, notification_type: 'like')
		notification.destroy if notification
	end

end

app/helpers/posts_helper.rb
module PostsHelper
	def like_toggle_path(post)
		like_toggle_path = if current_user.liked? post
												 dislike_post_path(post)
											 else
												 like_post_path(post)
											 end
	end

	def like_icon_for_post(post)
		if current_user.liked? post
			'glyphicon-heart'
		else
			'glyphicon-heart-empty'
		end
	end

	def display_likes(post)
		if post.get_likes.size < 9
			list_likers_of post
		else
			count_likers_of post
		end
	end

	def list_likers_of(post)
		# votes variable is set to the likes by users.
		votes = post.votes_for.up.by_type(User)
		# set user_names variable as an empty array
		user_names = []
		# unless there are no likes, continue below.
		unless votes.blank?
			# iterate through the voters of each vote (the users who liked the post)
			votes.voters.each do |voter|
				# add the user_name as a link to the array
				user_names.push(profile_link(voter))
			end
			# present the array as a nice sentence using the as_sentence method and also make it usable within our html.  Then call the like_plural method with the votes variable we set earlier as the argument.
			user_names.to_sentence.html_safe + like_plural(votes)
		end
	end

	def count_likers_of(post)
		'like'.pluralize(post.likes)
	end

	private

	def like_plural(votes)
		# If we more than one like for a post, use ' like this'
		return ' like this' if votes.count > 1
		# Otherwise, return ' likes this'
		' likes this'
	end
end

app/views/posts/_form.html.erb
<div class="posts-wrapper">
	<div class="post">
		<div class="post-body">
			<div class="image-wrap center">
				<%= form_image_select(@post) %>
				<%= simple_form_for @post, html: { multipart: true } do |f| %>
					<div class="row">
						<div class="col-md-12 text-center">
							<%= f.error_notification %>
						</div>
					</div>
					<div class="container-fluid">
						<div class="form-group text-center">
							<h4>Upload an image (this is required):</h4>
							<%= f.input :image, label: false, input_html: { onChange: 'loadFile(event)' } %>
						</div>
						<div class="form-group text-center">
							<%= f.input :caption, label: false, placeholder: 'Add your caption' %>
						</div>
						<div class="form-group text-center">
							<%= f.button :submit, class: 'btn-success btn-block' %>
						</div>
					</div>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_likes.html.erb
<div class="likes" id="likes_<%= post.id %>">
	<%= display_likes post %>
</div>

app/views/posts/_post.html.erb
<div class="posts-wrapper">
	<div class="post">
		<div class="post-head">
			<div class="thumb-img"></div>
			<%= profile_link(post.user) %>
			<div class="time-ago">
				<%= time_ago_in_words post.created_at %>
			</div>
		</div>
		<div class="image center-block">
			<%= link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post) %>
		</div>
		<div class="post-bottom">

			<%= render 'posts/likes', post: post %>

			<div class="caption">
				<%= profile_link(post.user) %>
				<%= post.caption %>
			</div>

			<div class="comments" id="comments_<%= post.id %>">
				<% if post.comments.any? %>
					<div class="paginator" id="#comments-paginator-<%= post.id %>">
						<% unless post.comments.count <= 4 %>
							<%= link_to "View all #{post.comments.count} comments", post_comments_path(post), remote: true, class: 'more-comments' %>
						<% end %>
					</div>
					<%= render post.comments.last(4), post: post %>
				<% end %>
			</div>
		</div>

		<div class="comment-like-form row">
			<div class="like-button col-sm-1">
				<%= link_to '', like_toggle_path(post), remote: true, id: "like_#{post.id}", class:"glyphicon #{like_icon_for_post post}" %>
			</div>
			<div class="comment-form col-sm-11">
				<%= form_for([post, post.comments.build], remote: true) do |f| %>
					<%= f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}" %>
				<% end %>
			</div>
		</div>
	</div>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
	<%= render 'post', post: post %>
<% end %>

app/views/posts/dislike.js.erb
// change heart icon
$("#like_<%= @post.id %>").removeClass('glyphicon-heart').addClass('glyphicon-heart-empty');

// change link
$("#like_<%= @post.id %>").attr("href", "<%= like_post_path @post %>")

// re-render likes information
$("#likes_<%= @post.id %>").html("<%= j render 'posts/likes', post: @post %>");

app/views/posts/edit.html.erb
<div class="form-wrapper">

	<%= render 'form' %>

	<div class="text-center edit-links">
		<%= link_to "Cancel", posts_path %>
		|
		<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
	</div>
</div>

app/views/posts/index.html.erb
<div id="posts">
	<%= render 'posts' %>
</div>
<div class="text-center" id="paginator">
	<%= link_to_next_page @posts, 'Load More', remote: true, id: 'load_more' %>
</div>

app/views/posts/index.js.erb
$('#posts').append("<%= escape_javascript(render 'posts') %>");
$('#paginator').html("<%= escape_javascript(link_to_next_page(@posts, 'Load More', remote: true, id: 'load_more')) %>");
if (!$('#load_more').length) { $('#paginator').remove(); }

app/views/posts/like.js.erb
// change heart icon
$("#like_<%= @post.id %>").removeClass('glyphicon-heart-empty').addClass('glyphicon-heart');

// change link
$("#like_<%= @post.id %>").attr("href", "<%= dislike_post_path @post %>")

// re-render likes information
$("#likes_<%= @post.id %>").html("<%= j render 'posts/likes', post: @post %>");

app/views/posts/new.html.erb
<div class="form-wrapper">

  <%= render 'form' %>

</div>

app/views/posts/show.html.erb
<%= render 'post', post: @post %>
<div class="text-center edit-links">
	<%= link_to "Cancel", posts_path %>

	<% if current_user.id == @post.user.id %>
		|
		<%= link_to "Edit Post", edit_post_path(@post) %>
	<% end %>
</div>